[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
actix-web = "3"
serde ={ version = "1.0.132", features = ["derive"] }
serde_json = "^1.0.41"
mockall = "0.11.0"