[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
infrastructure = { path = "../infrastructure" }
actix-web = "3"
serde ={ version = "1.0.132", features = ["derive"] }
serde_json = "^1.0.41"